export enum AutoFillMessageType {
  status,
  search,
  getCredentialsForUrl,
  copyField,
  lock,
  unlock,
  createEntry,
  getGroups,
  getNewEntryDefaults,
  generatePassword,
  getIcon,
  generatePasswordV2,
  getPasswordStrength,
  getNewEntryDefaultsV2,
  getFavourites,
  copyString,
}
